### ISSUE TITLE
Transceiver 

### ISSUE THREAD

**Issue by TangerineBaker** [mage-tearz/evenfall-issues#1]
Doesn't give benefit when killing NPCs.

**Comment by Creeper2750** [comment]
Transceiver is now properly giving bonus credits!      























































The Hivemind Grows

**Comment by Creeper2750** [comment]
{POINHOUPGBUIOLVBY(IHOPUV OP)I*YHV LUJ:KBNPIOU{G(PUYOBIU){_HB:LJJP"JKMP"BN(U)OPB N
