### ISSUE TITLE
Combine Terminal error

### ISSUE THREAD

**Issue by hl2male09** [mage-tearz/evenfall-issues#3]
[ERROR] gamemodes/impulse-hl2rp/plugins/combinereq/vgui/cl_requesitionstore.lua:82: bad argument #1 to 'ipairs' (table expected, got nil)
  1. ipairs - [C]:-1
   2. ConstructMenu - gamemodes/impulse-hl2rp/plugins/combinereq/vgui/cl_requesitionstore.lua:82
    3. unknown - gamemodes/impulse-hl2rp/plugins/combinereq/vgui/cl_requesitionstore.lua:217

Timer Failed! [Simple][@gamemodes/impulse-hl2rp/plugins/combinereq/vgui/cl_requesitionstore.lua (line 215)]

**Comment by mage-tearz** [comment]
This is a larger issue than I initially thought. Good catch!

**Comment by mage-tearz** [comment]
"my mortal fucking enemy, a comma" -Kumazaki Evenfall
